In [4]:
import pandas as pd
from openpyxl import load_workbook

In [19]:
data = pd.read_excel('../data/match_data_1.xlsx')
data['match'] = 1
data['rally'].fillna(method='ffill', inplace=True)
data['rally'] = data['rally'].astype(int)
data.head(10)

,match,rally,ball_round,roundscore_player,roundscore_opponent,player,server,ball_location_x,ball_location_y,ball_height,...,time,ball_type,launching_height,landing_location_x,landing_location_y,player_defend_x,player_defend_y,landing_height,winner,lose_reason
0,1,1,1,0,0,B,1,-47.500000,180.000000,100.000000,...,0.000000,發短球,NaN,166.975584,382.695252,260.177070,821.473839,0.0,NaN,NaN
1,1,1,2,0,0,A,2,22.678129,6.155891,141.087623,...,0.616667,長球,NaN,260.177070,980.473839,177.500000,315.000000,0.0,NaN,NaN
2,1,1,3,0,0,B,3,75.821706,467.161668,149.541064,...,2.150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,出界
3,1,2,1,1,0,A,1,7.500000,160.000000,100.000000,...,2.700000,發短球,NaN,122.858940,599.327769,96.671969,356.548975,0.0,NaN,NaN
4,1,2,2,0,1,B,2,-35.563241,6.284815,147.436638,...,3.216667,放小球,NaN,96.671969,356.548975,103.657340,544.890324,0.0,NaN,NaN
5,1,2,3,1,0,A,2,62.749423,6.933819,146.529285,...,4.016667,放小球,NaN,103.657340,544.890324,96.393906,421.014587,0.0,NaN,NaN
6,1,2,4,0,1,B,2,-75.029835,2.274113,148.063639,...,5.216667,放小球,NaN,96.393906,421.014587,139.753621,618.955226,0.0,NaN,NaN
7,1,2,5,1,0,A,2,77.350914,2.223579,147.939771,...,6.033333,殺球,NaN,139.753621,618.955226,227.097849,365.812153,0.0,NaN,NaN
8,1,2,6,0,1,B,2,-45.111134,112.458537,147.477919,...,6.950000,放小球,NaN,227.097849,365.812153,194.076354,583.787918,0.0,NaN,NaN
9,1,2,7,1,0,A,2,-8.673104,5.115897,149.576417,...,7.683333,挑球,NaN,194.076354,583.787918,-0.603097,266.280838,0.0,NaN,NaN

In [21]:
data.to_csv('../data/preprocessed_pass_1.csv', index=False)